trigger:
- main

stages:
- stage: build
  jobs:
  - job: build 
    pool:
      vmImage: ubuntu-latest
    steps: 
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '6'
    - task: Npm@1
      inputs:
        command: 'install'

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true


