trigger:
- main

stages:
- stage: build
  jobs:
  - job: build 
    pool:
      vmImage: ubuntu-latest
    steps: 
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '6'
    - task: Npm@1
      displayName: 'install npm'
      inputs:
        command: 'install'
        workingDir: 'upvote'

    - task: Npm@1
      displayName: 'build npm'
      inputs:
        command: 'custom'
        workingDir: 'upvote'
        customCommand: 'run build'
    
    
    
    


